export const countries = [
  { code: "af", name: "Afghanistan", tlds: [".af"] },
  { code: "al", name: "Albania", tlds: [".al"] },
  { code: "dz", name: "Algeria", tlds: [".dz"] },
  { code: "as", name: "American Samoa", tlds: [".as"] },
  { code: "ad", name: "Andorra", tlds: [".ad"] },
  { code: "ao", name: "Angola", tlds: [".ao"] },
  { code: "ai", name: "Anguilla", tlds: [".ai"] },
  { code: "aq", name: "Antarctica", tlds: [".aq"] },
  { code: "ag", name: "Antigua and Barbuda", tlds: [".ag"] },
  { code: "ar", name: "Argentina", tlds: [".ar"] },
  { code: "am", name: "Armenia", tlds: [".am"] },
  { code: "aw", name: "Aruba", tlds: [".aw"] },
  { code: "au", name: "Australia", tlds: [".au", ".com.au"] },
  { code: "at", name: "Austria", tlds: [".at"] },
  { code: "az", name: "Azerbaijan", tlds: [".az"] },
  { code: "bs", name: "Bahamas", tlds: [".bs"] },
  { code: "bh", name: "Bahrain", tlds: [".bh"] },
  { code: "bd", name: "Bangladesh", tlds: [".bd"] },
  { code: "bb", name: "Barbados", tlds: [".bb"] },
  { code: "by", name: "Belarus", tlds: [".by"] },
  { code: "be", name: "Belgium", tlds: [".be"] },
  { code: "bz", name: "Belize", tlds: [".bz"] },
  { code: "bj", name: "Benin", tlds: [".bj"] },
  { code: "bm", name: "Bermuda", tlds: [".bm"] },
  { code: "bt", name: "Bhutan", tlds: [".bt"] },
  { code: "bo", name: "Bolivia", tlds: [".bo"] },
  { code: "ba", name: "Bosnia and Herzegovina", tlds: [".ba"] },
  { code: "bw", name: "Botswana", tlds: [".bw"] },
  { code: "bv", name: "Bouvet Island", tlds: [".bv"] },
  { code: "br", name: "Brazil", tlds: [".br", ".com.br"] },
  { code: "io", name: "British Indian Ocean Territory", tlds: [".io"] },
  { code: "bn", name: "Brunei Darussalam", tlds: [".bn"] },
  { code: "bg", name: "Bulgaria", tlds: [".bg"] },
  { code: "bf", name: "Burkina Faso", tlds: [".bf"] },
  { code: "bi", name: "Burundi", tlds: [".bi"] },
  { code: "kh", name: "Cambodia", tlds: [".kh"] },
  { code: "cm", name: "Cameroon", tlds: [".cm"] },
  { code: "ca", name: "Canada", tlds: [".ca"] },
  { code: "cv", name: "Cabo Verde", tlds: [".cv"] },
  { code: "ky", name: "Cayman Islands", tlds: [".ky"] },
  { code: "cf", name: "Central African Republic", tlds: [".cf"] },
  { code: "td", name: "Chad", tlds: [".td"] },
  { code: "cl", name: "Chile", tlds: [".cl"] },
  { code: "cn", name: "China", tlds: [".cn"] },
  { code: "cx", name: "Christmas Island", tlds: [".cx"] },
  { code: "cc", name: "Cocos (Keeling) Islands", tlds: [".cc"] },
  { code: "co", name: "Colombia", tlds: [".co"] },
  { code: "km", name: "Comoros", tlds: [".km"] },
  { code: "cg", name: "Congo", tlds: [".cg"] },
  { code: "cd", name: "Congo, Democratic Republic of the", tlds: [".cd"] },
  { code: "ck", name: "Cook Islands", tlds: [".ck"] },
  { code: "cr", name: "Costa Rica", tlds: [".cr"] },
  { code: "ci", name: "Côte d'Ivoire", tlds: [".ci"] },
  { code: "hr", name: "Croatia", tlds: [".hr"] },
  { code: "cu", name: "Cuba", tlds: [".cu"] },
  { code: "cy", name: "Cyprus", tlds: [".cy"] },
  { code: "cz", name: "Czechia", tlds: [".cz"] },
  { code: "dk", name: "Denmark", tlds: [".dk"] },
  { code: "dj", name: "Djibouti", tlds: [".dj"] },
  { code: "dm", name: "Dominica", tlds: [".dm"] },
  { code: "do", name: "Dominican Republic", tlds: [".do"] },
  { code: "ec", name: "Ecuador", tlds: [".ec"] },
  { code: "eg", name: "Egypt", tlds: [".eg"] },
  { code: "sv", name: "El Salvador", tlds: [".sv"] },
  { code: "gq", name: "Equatorial Guinea", tlds: [".gq"] },
  { code: "er", name: "Eritrea", tlds: [".er"] },
  { code: "ee", name: "Estonia", tlds: [".ee"] },
  { code: "et", name: "Ethiopia", tlds: [".et"] },
  { code: "fk", name: "Falkland Islands", tlds: [".fk"] },
  { code: "fo", name: "Faroe Islands", tlds: [".fo"] },
  { code: "fj", name: "Fiji", tlds: [".fj"] },
  { code: "fi", name: "Finland", tlds: [".fi"] },
  { code: "fr", name: "France", tlds: [".fr"] },
  { code: "gf", name: "French Guiana", tlds: [".gf"] },
  { code: "pf", name: "French Polynesia", tlds: [".pf"] },
  { code: "tf", name: "French Southern Territories", tlds: [".tf"] },
  { code: "ga", name: "Gabon", tlds: [".ga"] },
  { code: "gm", name: "Gambia", tlds: [".gm"] },
  { code: "ge", name: "Georgia", tlds: [".ge"] },
  { code: "de", name: "Germany", tlds: [".de"] },
  { code: "gh", name: "Ghana", tlds: [".gh"] },
  { code: "gi", name: "Gibraltar", tlds: [".gi"] },
  { code: "gr", name: "Greece", tlds: [".gr"] },
  { code: "gl", name: "Greenland", tlds: [".gl"] },
  { code: "gd", name: "Grenada", tlds: [".gd"] },
  { code: "gp", name: "Guadeloupe", tlds: [".gp"] },
  { code: "gu", name: "Guam", tlds: [".gu"] },
  { code: "gt", name: "Guatemala", tlds: [".gt"] },
  { code: "gn", name: "Guinea", tlds: [".gn"] },
  { code: "gw", name: "Guinea-Bissau", tlds: [".gw"] },
  { code: "gy", name: "Guyana", tlds: [".gy"] },
  { code: "ht", name: "Haiti", tlds: [".ht"] },
  { code: "hm", name: "Heard Island and McDonald Islands", tlds: [".hm"] },
  { code: "va", name: "Holy See", tlds: [".va"] },
  { code: "hn", name: "Honduras", tlds: [".hn"] },
  { code: "hk", name: "Hong Kong", tlds: [".hk"] },
  { code: "hu", name: "Hungary", tlds: [".hu"] },
  { code: "is", name: "Iceland", tlds: [".is"] },
  { code: "in", name: "India", tlds: [".in", ".co.in"] },
  { code: "id", name: "Indonesia", tlds: [".id"] },
  { code: "ir", name: "Iran", tlds: [".ir"] },
  { code: "iq", name: "Iraq", tlds: [".iq"] },
  { code: "ie", name: "Ireland", tlds: [".ie"] },
  { code: "il", name: "Israel", tlds: [".il"] },
  { code: "it", name: "Italy", tlds: [".it"] },
  { code: "jm", name: "Jamaica", tlds: [".jm"] },
  { code: "jp", name: "Japan", tlds: [".jp", ".co.jp"] },
  { code: "jo", name: "Jordan", tlds: [".jo"] },
  { code: "kz", name: "Kazakhstan", tlds: [".kz"] },
  { code: "ke", name: "Kenya", tlds: [".ke"] },
  { code: "ki", name: "Kiribati", tlds: [".ki"] },
  { code: "kp", name: "Korea, Democratic People's Republic of", tlds: [".kp"] },
  { code: "kr", name: "Korea, Republic of", tlds: [".kr", ".co.kr"] },
  { code: "kw", name: "Kuwait", tlds: [".kw"] },
  { code: "kg", name: "Kyrgyzstan", tlds: [".kg"] },
  { code: "la", name: "Lao People's Democratic Republic", tlds: [".la"] },
  { code: "lv", name: "Latvia", tlds: [".lv"] },
  { code: "lb", name: "Lebanon", tlds: [".lb"] },
  { code: "ls", name: "Lesotho", tlds: [".ls"] },
  { code: "lr", name: "Liberia", tlds: [".lr"] },
  { code: "ly", name: "Libya", tlds: [".ly"] },
  { code: "li", name: "Liechtenstein", tlds: [".li"] },
  { code: "lt", name: "Lithuania", tlds: [".lt"] },
  { code: "lu", name: "Luxembourg", tlds: [".lu"] },
  { code: "mo", name: "Macao", tlds: [".mo"] },
  { code: "mk", name: "North Macedonia", tlds: [".mk"] },
  { code: "mg", name: "Madagascar", tlds: [".mg"] },
  { code: "mw", name: "Malawi", tlds: [".mw"] },
  { code: "my", name: "Malaysia", tlds: [".my"] },
  { code: "mv", name: "Maldives", tlds: [".mv"] },
  { code: "ml", name: "Mali", tlds: [".ml"] },
  { code: "mt", name: "Malta", tlds: [".mt"] },
  { code: "mh", name: "Marshall Islands", tlds: [".mh"] },
  { code: "mq", name: "Martinique", tlds: [".mq"] },
  { code: "mr", name: "Mauritania", tlds: [".mr"] },
  { code: "mu", name: "Mauritius", tlds: [".mu"] },
  { code: "yt", name: "Mayotte", tlds: [".yt"] },
  { code: "mx", name: "Mexico", tlds: [".mx", ".com.mx"] },
  { code: "fm", name: "Micronesia", tlds: [".fm"] },
  { code: "md", name: "Moldova", tlds: [".md"] },
  { code: "mc", name: "Monaco", tlds: [".mc"] },
  { code: "mn", name: "Mongolia", tlds: [".mn"] },
  { code: "ms", name: "Montserrat", tlds: [".ms"] },
  { code: "ma", name: "Morocco", tlds: [".ma"] },
  { code: "mz", name: "Mozambique", tlds: [".mz"] },
  { code: "mm", name: "Myanmar", tlds: [".mm"] },
  { code: "na", name: "Namibia", tlds: [".na"] },
  { code: "nr", name: "Nauru", tlds: [".nr"] },
  { code: "np", name: "Nepal", tlds: [".np"] },
  { code: "nl", name: "Netherlands", tlds: [".nl"] },
  { code: "an", name: "Netherlands Antilles", tlds: [".an"] },
  { code: "nc", name: "New Caledonia", tlds: [".nc"] },
  { code: "nz", name: "New Zealand", tlds: [".nz", ".co.nz"] },
  { code: "ni", name: "Nicaragua", tlds: [".ni"] },
  { code: "ne", name: "Niger", tlds: [".ne"] },
  { code: "ng", name: "Nigeria", tlds: [".ng"] },
  { code: "nu", name: "Niue", tlds: [".nu"] },
  { code: "nf", name: "Norfolk Island", tlds: [".nf"] },
  { code: "mp", name: "Northern Mariana Islands", tlds: [".mp"] },
  { code: "no", name: "Norway", tlds: [".no"] },
  { code: "om", name: "Oman", tlds: [".om"] },
  { code: "pk", name: "Pakistan", tlds: [".pk"] },
  { code: "pw", name: "Palau", tlds: [".pw"] },
  { code: "ps", name: "Palestine", tlds: [".ps"] },
  { code: "pa", name: "Panama", tlds: [".pa"] },
  { code: "pg", name: "Papua New Guinea", tlds: [".pg"] },
  { code: "py", name: "Paraguay", tlds: [".py"] },
  { code: "pe", name: "Peru", tlds: [".pe"] },
  { code: "ph", name: "Philippines", tlds: [".ph"] },
  { code: "pn", name: "Pitcairn", tlds: [".pn"] },
  { code: "pl", name: "Poland", tlds: [".pl"] },
  { code: "pt", name: "Portugal", tlds: [".pt"] },
  { code: "pr", name: "Puerto Rico", tlds: [".pr"] },
  { code: "qa", name: "Qatar", tlds: [".qa"] },
  { code: "re", name: "Réunion", tlds: [".re"] },
  { code: "ro", name: "Romania", tlds: [".ro"] },
  { code: "ru", name: "Russian Federation", tlds: [".ru"] },
  { code: "rw", name: "Rwanda", tlds: [".rw"] },
  { code: "sh", name: "Saint Helena, Ascension and Tristan da Cunha", tlds: [".sh"] },
  { code: "kn", name: "Saint Kitts and Nevis", tlds: [".kn"] },
  { code: "lc", name: "Saint Lucia", tlds: [".lc"] },
  { code: "pm", name: "Saint Pierre and Miquelon", tlds: [".pm"] },
  { code: "vc", name: "Saint Vincent and the Grenadines", tlds: [".vc"] },
  { code: "ws", name: "Samoa", tlds: [".ws"] },
  { code: "sm", name: "San Marino", tlds: [".sm"] },
  { code: "st", name: "Sao Tome and Principe", tlds: [".st"] },
  { code: "sa", name: "Saudi Arabia", tlds: [".sa"] },
  { code: "sn", name: "Senegal", tlds: [".sn"] },
  { code: "rs", name: "Serbia", tlds: [".rs"] },
  { code: "sc", name: "Seychelles", tlds: [".sc"] },
  { code: "sl", name: "Sierra Leone", tlds: [".sl"] },
  { code: "sg", name: "Singapore", tlds: [".sg"] },
  { code: "sk", name: "Slovakia", tlds: [".sk"] },
  { code: "si", name: "Slovenia", tlds: [".si"] },
  { code: "sb", name: "Solomon Islands", tlds: [".sb"] },
  { code: "so", name: "Somalia", tlds: [".so"] },
  { code: "za", name: "South Africa", tlds: [".za"] },
  { code: "gs", name: "South Georgia and the South Sandwich Islands", tlds: [".gs"] },
  { code: "es", name: "Spain", tlds: [".es"] },
  { code: "lk", name: "Sri Lanka", tlds: [".lk"] },
  { code: "sd", name: "Sudan", tlds: [".sd"] },
  { code: "sr", name: "Suriname", tlds: [".sr"] },
  { code: "sj", name: "Svalbard and Jan Mayen", tlds: [".sj"] },
  { code: "sz", name: "Eswatini", tlds: [".sz"] },
  { code: "se", name: "Sweden", tlds: [".se"] },
  { code: "ch", name: "Switzerland", tlds: [".ch"] },
  { code: "sy", name: "Syrian Arab Republic", tlds: [".sy"] },
  { code: "tw", name: "Taiwan", tlds: [".tw"] },
  { code: "tj", name: "Tajikistan", tlds: [".tj"] },
  { code: "tz", name: "Tanzania", tlds: [".tz"] },
  { code: "th", name: "Thailand", tlds: [".th"] },
  { code: "tl", name: "Timor-Leste", tlds: [".tl"] },
  { code: "tg", name: "Togo", tlds: [".tg"] },
  { code: "tk", name: "Tokelau", tlds: [".tk"] },
  { code: "to", name: "Tonga", tlds: [".to"] },
  { code: "tt", name: "Trinidad and Tobago", tlds: [".tt"] },
  { code: "tn", name: "Tunisia", tlds: [".tn"] },
  { code: "tr", name: "Türkiye", tlds: [".tr", ".com.tr"] },
  { code: "tm", name: "Turkmenistan", tlds: [".tm"] },
  { code: "tc", name: "Turks and Caicos Islands", tlds: [".tc"] },
  { code: "tv", name: "Tuvalu", tlds: [".tv"] },
  { code: "ug", name: "Uganda", tlds: [".ug"] },
  { code: "ua", name: "Ukraine", tlds: [".ua"] },
  { code: "ae", name: "United Arab Emirates", tlds: [".ae"] },
  { code: "gb", name: "United Kingdom", tlds: [".uk", ".gb", ".co.uk", ".org.uk", ".ac.uk"] },
  { code: "us", name: "United States", tlds: [".com", ".us"] },
  { code: "um", name: "United States Minor Outlying Islands", tlds: [".um"] },
  { code: "uy", name: "Uruguay", tlds: [".uy"] },
  { code: "uz", name: "Uzbekistan", tlds: [".uz"] },
  { code: "vu", name: "Vanuatu", tlds: [".vu"] },
  { code: "ve", name: "Venezuela", tlds: [".ve"] },
  { code: "vn", name: "Viet Nam", tlds: [".vn"] },
  { code: "vg", name: "Virgin Islands, British", tlds: [".vg"] },
  { code: "vi", name: "Virgin Islands, U.S.", tlds: [".vi"] },
  { code: "wf", name: "Wallis and Futuna", tlds: [".wf"] },
  { code: "eh", name: "Western Sahara", tlds: [".eh"] },
  { code: "ye", name: "Yemen", tlds: [".ye"] },
  { code: "zm", name: "Zambia", tlds: [".zm"] },
  { code: "zw", name: "Zimbabwe", tlds: [".zw"] }
];

export const languages = [
  { code: "en", name: "English" },
  { code: "de", name: "German" },
  { code: "fr", name: "French" },
  { code: "es", name: "Spanish" },
  { code: "it", name: "Italian" },
  { code: "nl", name: "Dutch" },
  { code: "tr", name: "Turkish" },
  { code: "pt", name: "Portuguese" },
  { code: "sv", name: "Swedish" },
  { code: "no", name: "Norwegian" },
  { code: "da", name: "Danish" },
  { code: "pl", name: "Polish" },
  { code: "ja", name: "Japanese" }
];

export function detectCountryFromUrl(urlString) {
  const hostname = new URL(urlString).hostname.toLowerCase();
  const matches = [];
  for (const country of countries) {
    for (const tld of country.tlds) {
      if (hostname.endsWith(tld)) {
        matches.push({ ...country, length: tld.length });
      }
    }
  }
  matches.sort((a, b) => b.length - a.length);
  return matches[0] ? { code: matches[0].code, name: matches[0].name } : { code: "us", name: "United States" };
}

export function normalizeLanguageCode(value) {
  if (!value) return "en";
  const lower = String(value).toLowerCase();
  const twoLetter = lower.split(/[-_]/)[0];
  return languages.some((language) => language.code === twoLetter) ? twoLetter : "en";
}
